### ISSUE TITLE
Method not found error on server start with Warfare update

### ISSUE THREAD

**Issue by Blaylock1988** [HnZGaming/TorchAutoModerator#1]
All of our sectors are getting the same error upon server start with this plugin.

```00:24:01.9631 [ERROR]  AutoModeratorPlugin: System.MissingMethodException: Method not found: 'Int64 Sandbox.Game.World.MyFaction.get_FactionId()'.
   at AutoModerator.Grids.GridLagTracker.Update(BaseProfilerResult`1 profileResult)
   at AutoModerator.AutoModeratorPlugin.<Main>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Utils.General.TaskUtils.<RunUntilCancelledAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Utils.General.TaskUtils.<Forget>d__0.MoveNext()
System.MissingMethodException: Method not found: 'Int64 Sandbox.Game.World.MyFaction.get_FactionId()'.
   at AutoModerator.Grids.GridLagTracker.Update(BaseProfilerResult`1 profileResult)
   at AutoModerator.AutoModeratorPlugin.<Main>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Utils.General.TaskUtils.<RunUntilCancelledAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Utils.General.TaskUtils.<Forget>d__0.MoveNext()```

**Comment by ryo0ka** [comment]
Fix is up on the discord channel. Will roll it out here soon as well
